In [1]:
import numpy as np

In [6]:
a=np.array([(1,2,3),(4,5,6)])

In [8]:
c=np.array([(1,2),(3,4)],dtype=complex)

In [15]:
d=np.zeros((2,3))
e=np.ones((2,3),dtype=np.int16)
f=np.empty((2,3),dtype=np.int32)

In [44]:
A=np.arange(4).reshape(2,2)
B=np.array([(1,0),(1,1)])
A,B

(array([[0, 1],
        [2, 3]]), array([[1, 0],
        [1, 1]]))

In [47]:
a=np.arange(1,4)
b=np.array([1,2,3])

In [48]:
a-b

array([0, 0, 0])

In [49]:
test=np.arange(12).reshape(3,4)


In [55]:
test

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
test.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [59]:
np.exp(test)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
          2.00855369e+01],
       [  5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
          1.09663316e+03],
       [  2.98095799e+03,   8.10308393e+03,   2.20264658e+04,
          5.98741417e+04]])

In [62]:
hjw=np.arange(12).reshape(3,2,2)

In [67]:
hjw[1,:,1]

array([5, 7])

In [68]:
hjw[:,:,1]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [72]:
hjw.resize(2,6)

In [73]:
hjw

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [74]:
a = np.array([4.,2.])
b=b = np.array([2.,8.])

In [82]:
np.column_stack((a[:,np.newaxis],b[:,np.newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [78]:
np.vstack((a,b))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [79]:
np.hstack((a,b))

array([ 4.,  2.,  2.,  8.])

In [87]:
np.row_stack((a[:,np.newaxis],b[:,np.newaxis]))

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

In [91]:
a=np.r_[1:5,1,1,4]

In [92]:
a

array([1, 2, 3, 4, 1, 1, 4])